// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSk2zjHIcC1Mb7qHFhIyPVo6wLr-Ikn6s',
    appId: '1:593829956242:web:194f789a0b5c167da3b44b',
    messagingSenderId: '593829956242',
    projectId: 'callvideo-2b9c5',
    authDomain: 'callvideo-2b9c5.firebaseapp.com',
    databaseURL: 'https://callvideo-2b9c5-default-rtdb.firebaseio.com',
    storageBucket: 'callvideo-2b9c5.appspot.com',
    measurementId: 'G-NG0VNNYQTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBixYXq3dhZeZq_WHK7biHgiVj2SJkZ2Gs',
    appId: '1:593829956242:android:324b03a66ce1feefa3b44b',
    messagingSenderId: '593829956242',
    projectId: 'callvideo-2b9c5',
    databaseURL: 'https://callvideo-2b9c5-default-rtdb.firebaseio.com',
    storageBucket: 'callvideo-2b9c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqX2REmiceybdKaeDucZxwDZBCjU8DAE',
    appId: '1:593829956242:ios:24c034849b1c4ec2a3b44b',
    messagingSenderId: '593829956242',
    projectId: 'callvideo-2b9c5',
    databaseURL: 'https://callvideo-2b9c5-default-rtdb.firebaseio.com',
    storageBucket: 'callvideo-2b9c5.appspot.com',
    iosBundleId: 'com.example.ckflutter',
  );
}
